name: main

on:
  push:
    branches:
      - '*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+([0-9]+)'
  pull_request:
    branches:
      - '*'

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install --no-interaction --all-extras
      - name: run pre-commit
        run: poetry run pre-commit run --all-files --show-diff-on-failure
